name: get-commit-hash
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:

    - name: Generate BUILD_ID
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

    - name: My step
      run: echo "${SHORT_SHA}"