name: get-commit-hash
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      # - name: set BUILD_ID env
      #   run: echo "BUILD_ID=git rev-parse --short $GITHUB_SHA" >> GITHUB_ENV

      # - name: print BUILD_ID
      #   run: echo "${BUILD_ID}"

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: My step
      run: myscript ${SHORT_SHA}