name: get-commit-hash
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: set env
        run: echo "BUILD_ID=git rev-parse --short $GITHUB_SHA" >> GITHUB_ENV

      - name: print
        run: echo "${BUILD_ID}"